#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '花 - ❓ lint ~ ❓ project - checking eslint for errors'
eslint src --ext .ts # `--fix` would normally be here but it should only print and not fix

echo '花 - ✔ lint ~ ❓ project - compiling project for errors'
tsc --noEmit

echo '花 - ✔ lint ~ ✔ project - we are done here'
