name: ESLint
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - 'LICENSE'
      - '**.md'
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installs all global packages
        run: npm i -g eslint

      - name: Installs local packages
        run: npm ci

      - name: Runs the linter
        run: eslint src --ext .ts
