name: ktlint
on:
  push:
    branches:
      - 'features/**'
      - 'side/**'
      - 'master'
      - 'dev'
    paths-ignore:
      - '.github/**'
      - 'gradle.properties'
      - 'LICENSE'
      - '**.md'
      - 'renovate.json'
  pull_request:
    branches:
      - 'features/**'
      - 'side/**'
      - 'master'
      - 'dev'
    paths-ignore:
      - '.github/**'
      - 'gradle.properties'
      - 'LICENSE'
      - '**.md'
      - 'renovate.json'
jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup JDK v1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Grant permissions to the build script
        run: chmod +x gradlew

      - name: Apply ktlint
        run: ./gradlew spotlessApply

      - name: Compile the project for any code errors
        run: ./gradlew build
